version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven
      - mvn --version
  build:
    commands:
      - echo Build started
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/demo-1.0.jar
  discard-paths: yes
